# Generated by Django 5.2.3 on 2025-08-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='number_rating',
        ),
    ]
